default: &default
  adapter: postgresql
  user: vendough_app
  password: <%= ENV['VENDOUGH_DATABASE_PASSWORD']  %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vendough_app_development

test:
  <<: *default
  database: vendough_app_test

production:
  <<: *default
  database: vendough_app_production
